name: gringo_qi_gong
description: A new Flutter project for Gringo-QI-Gong.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  video_player: ^2.8.2
  chewie: ^1.7.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
